# Generated by Django 5.2.4 on 2025-07-10 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_followedsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followed_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followedsource',
            unique_together={('user', 'source_name')},
        ),
    ]
