# Generated by Django 5.2.4 on 2025-07-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_followedsource_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowedSource',
        ),
    ]
