# Generated by Django 5.2.4 on 2025-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
