# Generated by Django 5.2.4 on 2025-07-12 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_language_headline_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
