# Generated by Django 5.2.4 on 2025-07-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_headline_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='created_at',
        ),
    ]
